repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^.+(\.md)$

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.1'
    hooks:
      - id: poetry-check
        args: [ "--lock" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.15.1'
    hooks:
      - id: pyupgrade
        args: [ --py312-plus ]
        files: ^(src|tests)/.+\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.0'
    hooks:
      - id: ruff
        files: ^(src|tests)/.+\.py$
        args: [ --fix ]
      - id: ruff-format
        files: ^(src|tests)/.+\.py$

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [ --line-length=120 ]
        exclude: ^.+(\.md)$
        files: ^(src|tests)/.+\.py$

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
